/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_project;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


    
public class StudentMarks extends javax.swing.JFrame {

    MyConnection mdc;
    Connection con;
    ResultSet rs;
    String examtype;
    String coursecode;
    
    public StudentMarks() {
        initComponents();
        setLocationRelativeTo(null);
        mdc = new MyConnection();
        con = (Connection) mdc.getConnection();
        setShape(new RoundRectangle2D.Double(0,0, getWidth(), getHeight(), 30, 30));
        //loaddata();
        

    }
    public StudentMarks(String coursecode,String examtype){
        initComponents();
        setLocationRelativeTo(null);
        mdc = new MyConnection();
        con = (Connection) mdc.getConnection();
        setShape(new RoundRectangle2D.Double(0,0, getWidth(), getHeight(), 30, 30));
        this.examtype = examtype;
        this.coursecode = coursecode;
        loaddata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Registration number", "Course code", "Marks"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void loaddata(){
        try{
            Statement stmt = con.createStatement();
            String myStatement;
            if(examtype.equals("Mid marks")){
                   myStatement = "SELECT * FROM tot_mid_marks WHERE course_code = '" + coursecode +"'";
                   DefaultTableModel dt2 = (DefaultTableModel) jTable1.getModel();
                   dt2.setRowCount(0);
                   ResultSet rs3 = stmt.executeQuery(myStatement);
                   while(rs3.next()){
                       Vector v2 = new Vector();
                       v2.add(rs3.getString(1));
                       v2.add(rs3.getString(2));
                       v2.add(rs3.getString(3));
                       dt2.addRow(v2);
                    }
            }
            else if(examtype.equals("Assessment")){
                   myStatement = "SELECT * FROM tot_assessment_marks WHERE course_code = '" + coursecode +"'";
                   DefaultTableModel dt2 = (DefaultTableModel) jTable1.getModel();
                   dt2.setRowCount(0);
                   ResultSet rs3 = stmt.executeQuery(myStatement);
                   while(rs3.next()){
                       Vector v2 = new Vector();
                       v2.add(rs3.getString(1));
                       v2.add(rs3.getString(2));
                       v2.add(rs3.getString(3));
                       dt2.addRow(v2);
                    }
            }
            else if(examtype.equals("Quiz marks")){
                   myStatement = "SELECT * FROM tot_quiz_marks WHERE course_code = '" + coursecode +"'";
                   DefaultTableModel dt2 = (DefaultTableModel) jTable1.getModel();
                   dt2.setRowCount(0);
                   ResultSet rs3 = stmt.executeQuery(myStatement);
                   while(rs3.next()){
                       Vector v2 = new Vector();
                       v2.add(rs3.getString(1));
                       v2.add(rs3.getString(2));
                       v2.add(rs3.getString(3));
                       dt2.addRow(v2);
                    }
            }
            else if(examtype.equals("Final marks")){
                   myStatement = "SELECT * FROM final_exam_results WHERE course_code = '" + coursecode +"'";
                   DefaultTableModel dt2 = (DefaultTableModel) jTable1.getModel();
                   dt2.setRowCount(0);
                   ResultSet rs3 = stmt.executeQuery(myStatement);
                   while(rs3.next()){
                       Vector v2 = new Vector();
                       v2.add(rs3.getString(1));
                       v2.add(rs3.getString(2));
                       v2.add(rs3.getString(3));
                       dt2.addRow(v2);
                    }
            }
            else if(examtype.equals("Final theory marks")){
                   myStatement = "SELECT * FROM final_marks WHERE course_code = '" + coursecode +"'";
                   DefaultTableModel dt2 = (DefaultTableModel) jTable1.getModel();
                   dt2.setRowCount(0);
                   ResultSet rs3 = stmt.executeQuery(myStatement);
                   while(rs3.next()){
                       Vector v2 = new Vector();
                       v2.add(rs3.getString(2));
                       v2.add(rs3.getString(3));
                       v2.add(rs3.getString(4));
                       dt2.addRow(v2);
                    }
            }
            else if(examtype.equals("Final practical marks")){
                   myStatement = "SELECT * FROM final_marks WHERE course_code = '" + coursecode +"'";
                   DefaultTableModel dt2 = (DefaultTableModel) jTable1.getModel();
                   dt2.setRowCount(0);
                   ResultSet rs3 = stmt.executeQuery(myStatement);
                   while(rs3.next()){
                       Vector v2 = new Vector();
                       v2.add(rs3.getString(2));
                       v2.add(rs3.getString(3));
                       v2.add(rs3.getString(5));
                       dt2.addRow(v2);
                    }
            }
            
           
            } catch(SQLException e) {
                System.out.println("Error with loading data!" + e.getMessage());
            } 
            catch(Exception e){
                System.out.println("Error " + e.getMessage());
            }finally {
                /*try {
                    con.close();
                }catch(SQLException e) {
                    System.out.println("Error in closing the connection " + e.getMessage());
                }*/
            }
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
